# Generated by Django 4.0.5 on 2022-06-18 21:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imagesapp', '0003_remove_thumbnail_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('expire_after', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(30000), django.core.validators.MinValueValidator(300)])),
                ('original_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temps', to='imagesapp.image')),
            ],
        ),
    ]
