# Generated by Django 4.0.5 on 2022-06-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='thumbnail name')),
                ('height', models.IntegerField(verbose_name='thumbnail height')),
            ],
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='tier name')),
                ('original_link_visible', models.BooleanField(default=False, verbose_name='original link visibility')),
                ('expireable', models.BooleanField(default=False, verbose_name='expireable')),
                ('thumbnails', models.ManyToManyField(related_name='tiers', to='tiersapp.thumbnail')),
            ],
        ),
    ]
